/**
 * Created by jack on 2016/10/19.
 */
export const USER_CENTER_UPDATE = 'USER_CENTER_UPDATE';
export const USER_CENTER_STORE_UPDATE_WEITUAN_ADDRESS = 'USER_CENTER_STORE_UPDATE_WEITUAN_ADDRESS';
export const USER_CENTER_STORE_UPDATE_ORDER_STATE = 'USER_CENTER_STORE_UPDATE_ORDER_STATE';
