const actionTypes = {
    'COUNTER_INCREMENT': 'COUNTER_INCREMENT',
    'COUNTER_DECREMENT': 'COUNTER_DECREMENT',
    
    'TODO_ADD': 'TODO_ADD',
    'TODO_TOGGLE': 'TODO_TOGGLE',
    'TODO_REMOVE': 'TODO_REMOVE',
    'TODO_SHOW_ALL': 'TODO_SHOW_ALL',
    'TODO_SHOW_ACTIVE': 'TODO_SHOW_ACTIVE',
    'TODO_SHOW_COMPLETED': 'TODO_SHOW_COMPLETED',
    'TODO_SET_VISIBILITY': 'TODO_SET_VISIBILITY',
};


export default actionTypes;